package com.taskify.task.exception.response;

public class ResponseMessage {

    public final static String ERROR_ACCOUNT_NOT_FOUND_BY_ID = "Account not found with given id";
    public final static String ERROR_TASK_NOT_FOUND_BY_ID = "Task not found with given id";
    public final static String ERROR_TASK_IS_ALREADY_ASSIGNED_TO_ACCOUNT = "Task is already assigned to the account";
    public final static String ERROR_INTERNAL_SERVER_ERROR = "Internal server error";
}
